image:
  tag: v3.0.0-beta2
logs:
  general:
    level: DEBUG
  access:
    enabled: true
service:
  type: NodePort
additionalArguments:
  - "--entryPoints.postgresql.address=:5432/tcp"
ports:
  postgresql:
    expose: true
    port: 5432
    exposedPort: 5432
    nodePort: 32432
    protocol: TCP
deployment:
  replicas: 1
