version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    # ports:
    #   - "8000:8000" # Adjust the ports as per your application's needs

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
