version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  hello-world-client:
    image: curlimages/curl
    depends_on:
      - app
    command: /bin/sh -c "while true; do sleep 1; curl -s http://app:8080/; done"

  health-check-client:
    image: curlimages/curl
    depends_on:
      - app
    command: /bin/sh -c "while true; do sleep 1; curl -s http://app:8080/lively; done"
